package com.eit.brnnda.dataclass

data class ProductDetailsData(
    val cashback: Int,
    val catalog_id: Int,
    val category_id: Int,
    val childcategory_id: Any,
    val color: List<String>,
    val details: String,
    val discount_date: Any,
    val featured: Int,
    val features: String,
    val gallery: List<String>,
    val id: Int,
    val is_catalog: Int,
    val is_discount: Int,
    val measure: Any,
    val name: String,
    val photo: String,
    val previous_price: Int,
    val price: Int,
    val product_condition: Int,
    val product_payment_method: Int,
    val product_type: String,
    val ship: String,
    val sku: String,
    val slug: String,
    val status: Int,
    val stock: Any,
    val subcategory_id: Int,
    val thumbnail: String,
    val type: String,
    val user_id: Int,
    val views: Int,
    val youtube: String,
    val product_tax: String,
    val product_tax_status: String
)